### ISSUE TITLE
May I ask when the code will be open-sourced?

### ISSUE THREAD

**Issue by TongWang-CN** [FeiLiu36/PromptVRP#1]
Hi, Dr.Liu! May I ask when the code will be open-sourced?

**Comment by FeiLiu36** [comment]
Thank you for your interest in our work!  We have just uploaded the main part of the source code.

**Comment by TongWang-CN** [comment]
> Thank you for your interest in our work! We have just uploaded the main part of the source code.

Thanks！😀
